//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellableMVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [Display(Name = "Order ID")]
        public int OrderID { get; set; }

        public decimal Amount { get; set; }

        public int UserId { get; set; }

        public int OrderStatusId { get; set; }

        [Display(Name = "Create Date")]
        public System.DateTime CreateDate { get; set; }

        [Display(Name = "Created By")]
        public string CreateBy { get; set; }

        public Nullable<int> PaymentTypeId { get; set; }

        public Nullable<int> PromoId { get; set; }

        public Nullable<int> UserPhoneId { get; set; }

        [Display(Name = "Payment User Name")]
        public string PaymentUserName { get; set; }

        [Display(Name = "USPS Tracking ID")]
        public string USPSTrackingId { get; set; }
    
        public virtual User User { get; set; }

        [Display(Name = "Order Status")]
        public virtual OrderStatu OrderStatu { get; set; }

        [Display(Name = "Payment Type")]
        public virtual PaymentType PaymentType { get; set; }

        public virtual Promo Promo { get; set; }
    }
}
