//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellableMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SlideShow
    {
        [Display(Name = "Slide ID")]
        public int SlideId { get; set; }

        [Display(Name = "Image Name")]
        public string ImageName { get; set; }

        public string Description { get; set; }
    }
}
