//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellableMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class State
    {
        [Display(Name = "State ID")]
        public int StateID { get; set; }

        [Display(Name = "State Abbrv")]
        public string StateAbbrv { get; set; }

        [Display(Name = "State Name")]
        public string StateName { get; set; }
    }
}
